class VideoModel{
  final String title;
  final String channelName;
  final String channelProfilePic;
  final String thumbnail;
  final String videoUrl;
  final String views;
  final String timeUploaded;
  final String duration;
  final String likes;
  final String dislikes;
  final String subscribers;

  const VideoModel({
    required this.title,
    required this.channelName,
    required this.channelProfilePic,
    required this.thumbnail,
    required this.videoUrl,
    required this.views,
    required this.timeUploaded,
    required this.duration,
    required this.likes,
    required this.dislikes,
    required this.subscribers,
  });
}

const List<VideoModel> videoList = [
  VideoModel(
    title: "Roadmap to learn Flutter | For all Developers",
    channelName: "Codepur",
    channelProfilePic: "https://yt3.googleusercontent.com/pHX8Ma1wLehHZFTQyBl5Q6l-akiTV9wdM68OtcJqRDMQC7ztLqLk-P_DBOYpr_4zplDfnhaimA=s176-c-k-c0x00ffffff-no-rj",
    thumbnail: "https://img.youtube.com/vi/7660DZ_HJqM/maxresdefault.jpg",
    views: "93k",
    timeUploaded: "1 year",
    duration: "24:21",
    videoUrl: "https://www.youtube.com/watch?v=7660DZ_HJqM&",
    likes: "26k",
    dislikes: "101",
    subscribers: "130K",
  ),
  VideoModel(
    title: "Apple Notes App • Flutter Tutorial",
    channelName: "Mitch Koko",
    channelProfilePic: "https://yt3.googleusercontent.com/ytc/AL5GRJX1cwt67aBPdhITea4cHCgahW2kooFPycmpv7Qiew=s176-c-k-c0x00ffffff-no-rj",
    thumbnail: "https://img.youtube.com/vi/BUCCHdKwKxE/maxresdefault.jpg",
    views: "4.9k",
    timeUploaded: "3 weeks",
    duration: "20:58",
    videoUrl: "https://www.youtube.com/watch?v=BUCCHdKwKxE",
    likes: "984",
    dislikes: "24",
    subscribers: "50K",
  ),
  VideoModel(
      title: "Building your first Flutter App - with a Codelab!",
      channelName: "Flutter",
      channelProfilePic: "https://yt3.googleusercontent.com/ytc/AL5GRJVFUbrqLgTKs3qvoiGiZDvJHXkB_pzHwyussmGX=s176-c-k-c0x00ffffff-no-rj",
      thumbnail: "https://img.youtube.com/vi/8sAyPDLorek/maxresdefault.jpg",
      views: "48k",
      timeUploaded: "2 weeks",
      duration: "1:32:01",
      videoUrl: "https://www.youtube.com/watch?v=8sAyPDLorek",
      likes: "11k",
      dislikes: "336",
      subscribers: "260K",
  ),
  VideoModel(
      title: "Flutter Provider State Management in 7 minutes",
      channelName: "Rivaan Ranawat",
      channelProfilePic: "https://yt3.googleusercontent.com/lbN9xUcA3Z830F-Z-O29URzACINv3kJiDua_omG1wwogcDWwXLQoyPzWH_v7ism34IvM09ApgQ=s176-c-k-c0x00ffffff-no-rj",
      thumbnail: "https://img.youtube.com/vi/uWlw3gEl4io/maxresdefault.jpg",
      views: "4.7k",
      timeUploaded: "6 months",
      duration: "7:01",
      videoUrl: "https://www.youtube.com/watch?v=uWlw3gEl4io",
      likes: "1.2k",
      dislikes: "15",
      subscribers: "35.6K",
  ),
  VideoModel(
      title: "1 on 1 Video Call App using ZEGOCLOUD in Flutter",
      channelName: "Rohit Semriwal",
      channelProfilePic: "https://yt3.googleusercontent.com/HCw-3yfLZL97NCGQM41uhpLjLlOq0bT5Z3XjINf4Q0nH1P_VpeoywVmECNBIyw5BleWfg-w-cg=s176-c-k-c0x00ffffff-no-rj",
      thumbnail: "https://img.youtube.com/vi/W7NMb4wkF1g/maxresdefault.jpg",
      views: "746",
      timeUploaded: "2 months",
      duration: "19:05",
      videoUrl: "https://www.youtube.com/watch?v=W7NMb4wkF1g",
      likes: "85",
      dislikes: "03",
      subscribers: "10.5K",
  ),
  VideoModel(
    title: "How I learned Flutter in 7 Days",
    channelName: "Kenny Gunderman",
    channelProfilePic: "https://yt3.googleusercontent.com/KLwRgRv9H5yVpqiPdwByE58xILzHnALi51XqFAdH4FwDDyV-8OmuiI7V7uFvxyEQdXD-EIpeODY=s176-c-k-c0x00ffffff-no-rj",
    thumbnail: "https://img.youtube.com/vi/RGdg-TCmldY/maxresdefault.jpg",
    views: "430k",
    timeUploaded: "1 year",
    duration: "8:26",
    videoUrl: "https://www.youtube.com/watch?v=RGdg-TCmldY",
    likes: "115k",
    dislikes: "5k",
    subscribers: "1.2M",
  ),
];

const List<VideoModel> shortList = [
  VideoModel(
    title: "Flutter Widget Explained",
    channelName: "",
    channelProfilePic: "",
    thumbnail: "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/content/og_image_file/og_image/1096555/0408-FlutterMessangerDemo-Luke_Social-e8a0e8ddab86b503a125ebcad823c583.png",
    views: "48k",
    timeUploaded: "",
    duration: "",
    videoUrl: "https://www.youtube.com/watch?v=YMx8Bbev6T4",
    likes: "15k",
    dislikes: "1k",
    subscribers: "130k",
  ),
  VideoModel(
    title: "Counter Strike 2",
    channelName: "",
    channelProfilePic: "",
    thumbnail: "https://s.yimg.com/uu/api/res/1.2/Zy2yByTqcSQzJYr2aO7znA--~B/Zmk9ZmlsbDtoPTU0Nzt3PTg3NTthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2023-03/67d201d0-c8dc-11ed-af67-655e1c3f5d72.cf.jpg",
    views: "16k",
    timeUploaded: "",
    duration: "",
    videoUrl: "https://www.youtube.com/watch?v=YMx8Bbev6T4",
    likes: "5.6k",
    dislikes: "954",
    subscribers: "130k",
  ),
  VideoModel(
    title: "My Channel got hacked",
    channelName: "",
    channelProfilePic: "",
    thumbnail: "https://pbs.twimg.com/media/Es9CrQtUYAM01oU.jpg",
    views: "895k",
    timeUploaded: "",
    duration: "",
    videoUrl: "https://www.youtube.com/watch?v=YMx8Bbev6T4",
    likes: "",
    dislikes: "",
    subscribers: "130k",
  ),
  VideoModel(
    title: "Meet Shiba Ninja",
    channelName: "",
    channelProfilePic: "",
    thumbnail: "https://pbs.twimg.com/profile_images/1396767577/ninjakoshi_400x400.jpg",
    views: "455k",
    timeUploaded: "",
    duration: "",
    videoUrl: "https://www.youtube.com/watch?v=YMx8Bbev6T4",
    likes: "",
    dislikes: "",
    subscribers: "130k",
  ),
  VideoModel(
    title: "Best Hiking Areas",
    channelName: "",
    channelProfilePic: "",
    thumbnail: "https://i0.wp.com/theoverlyopinionated.com/wp-content/uploads/2019/04/IMG_0678.jpg?resize=2000%2C1200&ssl=1",
    views: "21k",
    timeUploaded: "",
    duration: "",
    videoUrl: "https://www.youtube.com/watch?v=YMx8Bbev6T4",
    likes: "",
    dislikes: "",
    subscribers: "130k",
  ),
];